//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("TUModel", "FK__Movie__Main_Acto__12FDD1B2", "Actor", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(TUModel.Actor), "Movie", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TUModel.Movie), true)]
[assembly: EdmRelationshipAttribute("TUModel", "FK__Participa__Actor__16CE6296", "Actor", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(TUModel.Actor), "Participation", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TUModel.Participation), true)]
[assembly: EdmRelationshipAttribute("TUModel", "FK__Participa__Movie__15DA3E5D", "Movie", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(TUModel.Movie), "Participation", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TUModel.Participation), true)]

#endregion

namespace TUModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TUEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TUEntities object using the connection string found in the 'TUEntities' section of the application configuration file.
        /// </summary>
        public TUEntities() : base("name=TUEntities", "TUEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TUEntities object.
        /// </summary>
        public TUEntities(string connectionString) : base(connectionString, "TUEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TUEntities object.
        /// </summary>
        public TUEntities(EntityConnection connection) : base(connection, "TUEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Actor> Actors
        {
            get
            {
                if ((_Actors == null))
                {
                    _Actors = base.CreateObjectSet<Actor>("Actors");
                }
                return _Actors;
            }
        }
        private ObjectSet<Actor> _Actors;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Movie> Movies
        {
            get
            {
                if ((_Movies == null))
                {
                    _Movies = base.CreateObjectSet<Movie>("Movies");
                }
                return _Movies;
            }
        }
        private ObjectSet<Movie> _Movies;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Participation> Participations
        {
            get
            {
                if ((_Participations == null))
                {
                    _Participations = base.CreateObjectSet<Participation>("Participations");
                }
                return _Participations;
            }
        }
        private ObjectSet<Participation> _Participations;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Actors EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToActors(Actor actor)
        {
            base.AddObject("Actors", actor);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Movies EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMovies(Movie movie)
        {
            base.AddObject("Movies", movie);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Participations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToParticipations(Participation participation)
        {
            base.AddObject("Participations", participation);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TUModel", Name="Actor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Actor : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Actor object.
        /// </summary>
        /// <param name="actor_ID">Initial value of the Actor_ID property.</param>
        public static Actor CreateActor(global::System.Int32 actor_ID)
        {
            Actor actor = new Actor();
            actor.Actor_ID = actor_ID;
            return actor;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Actor_ID
        {
            get
            {
                return _Actor_ID;
            }
            set
            {
                if (_Actor_ID != value)
                {
                    OnActor_IDChanging(value);
                    ReportPropertyChanging("Actor_ID");
                    _Actor_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Actor_ID");
                    OnActor_IDChanged();
                }
            }
        }
        private global::System.Int32 _Actor_ID;
        partial void OnActor_IDChanging(global::System.Int32 value);
        partial void OnActor_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Surname
        {
            get
            {
                return _Surname;
            }
            set
            {
                OnSurnameChanging(value);
                ReportPropertyChanging("Surname");
                _Surname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Surname");
                OnSurnameChanged();
            }
        }
        private global::System.String _Surname;
        partial void OnSurnameChanging(global::System.String value);
        partial void OnSurnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Birthdate
        {
            get
            {
                return _Birthdate;
            }
            set
            {
                OnBirthdateChanging(value);
                ReportPropertyChanging("Birthdate");
                _Birthdate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Birthdate");
                OnBirthdateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Birthdate;
        partial void OnBirthdateChanging(Nullable<global::System.DateTime> value);
        partial void OnBirthdateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TUModel", "FK__Movie__Main_Acto__12FDD1B2", "Movie")]
        public EntityCollection<Movie> Movies
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Movie>("TUModel.FK__Movie__Main_Acto__12FDD1B2", "Movie");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Movie>("TUModel.FK__Movie__Main_Acto__12FDD1B2", "Movie", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TUModel", "FK__Participa__Actor__16CE6296", "Participation")]
        public EntityCollection<Participation> Participations
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Participation>("TUModel.FK__Participa__Actor__16CE6296", "Participation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Participation>("TUModel.FK__Participa__Actor__16CE6296", "Participation", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TUModel", Name="Movie")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Movie : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Movie object.
        /// </summary>
        /// <param name="movie_ID">Initial value of the Movie_ID property.</param>
        public static Movie CreateMovie(global::System.Int32 movie_ID)
        {
            Movie movie = new Movie();
            movie.Movie_ID = movie_ID;
            return movie;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Movie_ID
        {
            get
            {
                return _Movie_ID;
            }
            set
            {
                if (_Movie_ID != value)
                {
                    OnMovie_IDChanging(value);
                    ReportPropertyChanging("Movie_ID");
                    _Movie_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Movie_ID");
                    OnMovie_IDChanged();
                }
            }
        }
        private global::System.Int32 _Movie_ID;
        partial void OnMovie_IDChanging(global::System.Int32 value);
        partial void OnMovie_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Main_Actor_ID
        {
            get
            {
                return _Main_Actor_ID;
            }
            set
            {
                OnMain_Actor_IDChanging(value);
                ReportPropertyChanging("Main_Actor_ID");
                _Main_Actor_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Main_Actor_ID");
                OnMain_Actor_IDChanged();
            }
        }
        private Nullable<global::System.Int32> _Main_Actor_ID;
        partial void OnMain_Actor_IDChanging(Nullable<global::System.Int32> value);
        partial void OnMain_Actor_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Publish_Studio_ID
        {
            get
            {
                return _Publish_Studio_ID;
            }
            set
            {
                OnPublish_Studio_IDChanging(value);
                ReportPropertyChanging("Publish_Studio_ID");
                _Publish_Studio_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Publish_Studio_ID");
                OnPublish_Studio_IDChanged();
            }
        }
        private Nullable<global::System.Int32> _Publish_Studio_ID;
        partial void OnPublish_Studio_IDChanging(Nullable<global::System.Int32> value);
        partial void OnPublish_Studio_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Date_Published
        {
            get
            {
                return _Date_Published;
            }
            set
            {
                OnDate_PublishedChanging(value);
                ReportPropertyChanging("Date_Published");
                _Date_Published = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date_Published");
                OnDate_PublishedChanged();
            }
        }
        private Nullable<global::System.DateTime> _Date_Published;
        partial void OnDate_PublishedChanging(Nullable<global::System.DateTime> value);
        partial void OnDate_PublishedChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TUModel", "FK__Movie__Main_Acto__12FDD1B2", "Actor")]
        public Actor Actor
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Actor>("TUModel.FK__Movie__Main_Acto__12FDD1B2", "Actor").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Actor>("TUModel.FK__Movie__Main_Acto__12FDD1B2", "Actor").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Actor> ActorReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Actor>("TUModel.FK__Movie__Main_Acto__12FDD1B2", "Actor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Actor>("TUModel.FK__Movie__Main_Acto__12FDD1B2", "Actor", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TUModel", "FK__Participa__Movie__15DA3E5D", "Participation")]
        public EntityCollection<Participation> Participations
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Participation>("TUModel.FK__Participa__Movie__15DA3E5D", "Participation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Participation>("TUModel.FK__Participa__Movie__15DA3E5D", "Participation", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TUModel", Name="Participation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Participation : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Participation object.
        /// </summary>
        /// <param name="participation_ID">Initial value of the Participation_ID property.</param>
        public static Participation CreateParticipation(global::System.Int32 participation_ID)
        {
            Participation participation = new Participation();
            participation.Participation_ID = participation_ID;
            return participation;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Participation_ID
        {
            get
            {
                return _Participation_ID;
            }
            set
            {
                if (_Participation_ID != value)
                {
                    OnParticipation_IDChanging(value);
                    ReportPropertyChanging("Participation_ID");
                    _Participation_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Participation_ID");
                    OnParticipation_IDChanged();
                }
            }
        }
        private global::System.Int32 _Participation_ID;
        partial void OnParticipation_IDChanging(global::System.Int32 value);
        partial void OnParticipation_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Movie_ID
        {
            get
            {
                return _Movie_ID;
            }
            set
            {
                OnMovie_IDChanging(value);
                ReportPropertyChanging("Movie_ID");
                _Movie_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Movie_ID");
                OnMovie_IDChanged();
            }
        }
        private Nullable<global::System.Int32> _Movie_ID;
        partial void OnMovie_IDChanging(Nullable<global::System.Int32> value);
        partial void OnMovie_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Actor_ID
        {
            get
            {
                return _Actor_ID;
            }
            set
            {
                OnActor_IDChanging(value);
                ReportPropertyChanging("Actor_ID");
                _Actor_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Actor_ID");
                OnActor_IDChanged();
            }
        }
        private Nullable<global::System.Int32> _Actor_ID;
        partial void OnActor_IDChanging(Nullable<global::System.Int32> value);
        partial void OnActor_IDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TUModel", "FK__Participa__Actor__16CE6296", "Actor")]
        public Actor Actor
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Actor>("TUModel.FK__Participa__Actor__16CE6296", "Actor").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Actor>("TUModel.FK__Participa__Actor__16CE6296", "Actor").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Actor> ActorReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Actor>("TUModel.FK__Participa__Actor__16CE6296", "Actor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Actor>("TUModel.FK__Participa__Actor__16CE6296", "Actor", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TUModel", "FK__Participa__Movie__15DA3E5D", "Movie")]
        public Movie Movie
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Movie>("TUModel.FK__Participa__Movie__15DA3E5D", "Movie").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Movie>("TUModel.FK__Participa__Movie__15DA3E5D", "Movie").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Movie> MovieReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Movie>("TUModel.FK__Participa__Movie__15DA3E5D", "Movie");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Movie>("TUModel.FK__Participa__Movie__15DA3E5D", "Movie", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
